version: '3'

services:
  ng-mmi-dev:
    image: ng-mmi-dev
    build:
      context: ./mmi-assess
      dockerfile: Dockerfile
    container_name: mmi-frontend-container
    volumes:
      - "./mmi-assess/src:/app/src"
    environment:
      ENV: 'development'
      CHROME_BIN: '/usr/bin/chromium-browser'
      CHROME_PATH: '/usr/lib/chromium/'
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
    ports:
      - 3001:4200
    networks:
      - frontend
  mmi-api-dev:
    image: mmi-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mmi-api-container
    environment:
      ENV: 'development'
    ports:
      - 3002:52626
      - 3003:44344
      - 3004:80
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge