apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mmi-api-dev
  name: mmi-api-dev
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 52626
  - name: "3003"
    port: 3003
    targetPort: 44344
  - name: "3004"
    port: 3004
    targetPort: 80
  selector:
    io.kompose.service: mmi-api-dev
status:
  loadBalancer: {}
