apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mmi-api-dev
  name: mmi-api-dev
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mmi-api-dev
    spec:
      containers:
      - env:
        - name: ENV
          value: development
        image: mmi-api-dev
        name: mmi-api-container
        ports:
        - containerPort: 52626
        - containerPort: 44344
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
